#!/usr/bin/env python3
"""Runs the PGO training workload for one Pyronaut native image.

The workload drives the real ``pyronaut`` CLI (from source) so that training follows the same
command lines as users. Every launcher process started for the image under training goes through
a shim that adds ``-XX:ProfilesDumpFile=<profiles>/<scenario>-<pid>.iprof``, so that no process
overwrites another's profile. Servers are stopped with SIGTERM, which runs the shutdown hooks and
writes the profile.

With ``--jvm`` the same scenarios run against the JVM launchers and no profiles are collected.
That is how the workload itself is developed and checked without building native images.
"""
from __future__ import annotations

import argparse
import http.client
import json
import os
import random
import shutil
import signal
import socket
import stat
import subprocess
import sys
import threading
import time
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path

IMAGES = ("pyronaut-dev", "pyronaut-run", "pyronaut-run-python")
# The pyronaut-run workload. It must be a Maven or Gradle project, not a pyproject.toml project.
RUN_APP = "java-maven"
SPECIES = ("dog", "cat", "rabbit", "parrot", "hamster", "lizard")
NAMES = ("Rex", "Tom", "Bella", "Coco", "Milo", "Luna", "Max", "Daisy", "Oscar", "Ruby")

INSTRUMENTED_SHIM = """#!/bin/sh
# Generated by pgo_train.py: give every launcher process its own PGO profile.
scenario="${PGO_SCENARIO:-unscoped}"
mkdir -p "$PGO_PROFILES_DIR" "$PGO_PIDS_DIR"
echo $$ >> "$PGO_PIDS_DIR/$scenario.pids"
exec "@EXECUTABLE@" "-XX:ProfilesDumpFile=$PGO_PROFILES_DIR/$scenario-$$.iprof" "$@"
"""

WINDOWS_INSTRUMENTED_SHIM = """import os
import subprocess
import sys
import uuid
from pathlib import Path

scenario = os.environ.get("PGO_SCENARIO", "unscoped")
profiles = Path(os.environ["PGO_PROFILES_DIR"])
pids = Path(os.environ["PGO_PIDS_DIR"])
profiles.mkdir(parents=True, exist_ok=True)
pids.mkdir(parents=True, exist_ok=True)
profile = profiles / f"{scenario}-{uuid.uuid4().hex}.iprof"
process = subprocess.Popen(
    [@EXECUTABLE@, f"-XX:ProfilesDumpFile={profile}", *sys.argv[1:]],
    creationflags=subprocess.CREATE_NEW_PROCESS_GROUP,
)
with (pids / f"{scenario}.pids").open("a", encoding="utf-8") as stream:
    stream.write(f"{process.pid}\\t{profile.name}\\n")
with (pids / f"{scenario}.children.pids").open("a", encoding="utf-8") as stream:
    stream.write(f"{process.pid}\\n")
raise SystemExit(process.wait())
"""

# The CLI passes native-launcher style leading -D/-XX options, which the Gradle start script
# cannot take, so the JVM pyronaut-dev is started directly.
JVM_DEV_SHIM = """#!/bin/bash
# Generated by pgo_train.py: a JVM pyronaut-dev that accepts native-launcher arguments.
jvm_args=()
while [ $# -gt 0 ]; do
  case "$1" in
    -D*|-XX*) jvm_args+=("$1"); shift ;;
    *) break ;;
  esac
done
exec "$JAVA_HOME/bin/java" --sun-misc-unsafe-memory-access=allow --enable-native-access=ALL-UNNAMED \\
  ${jvm_args[@]+"${jvm_args[@]}"} -cp "@LIB@/*" io.micronaut.pyronaut.dev.PyronautDevMain "$@"
"""

WINDOWS_JVM_DEV_SHIM = """import os
import subprocess
import sys
from pathlib import Path

arguments = sys.argv[1:]
jvm_args = []
while arguments and (arguments[0].startswith("-D") or arguments[0].startswith("-XX")):
    jvm_args.append(arguments.pop(0))
command = [
    @JAVA@,
    "--sun-misc-unsafe-memory-access=allow",
    "--enable-native-access=ALL-UNNAMED",
    *jvm_args,
    "-cp",
    @CLASSPATH@,
    "io.micronaut.pyronaut.dev.PyronautDevMain",
    *arguments,
]
process = subprocess.Popen(command, creationflags=subprocess.CREATE_NEW_PROCESS_GROUP)
scenario = os.environ.get("PGO_SCENARIO")
if scenario:
    pids = Path(os.environ["PGO_PIDS_DIR"])
    pids.mkdir(parents=True, exist_ok=True)
    with (pids / f"{scenario}.children.pids").open("a", encoding="utf-8") as stream:
        stream.write(f"{process.pid}\\n")
raise SystemExit(process.wait())
"""


def _process_group_options() -> dict:
    if os.name == "nt":
        return {"creationflags": subprocess.CREATE_NEW_PROCESS_GROUP}
    return {"start_new_session": True}


class TrainingError(RuntimeError):
    pass


def log(message: str) -> None:
    print(f"[pgo-train {time.strftime('%H:%M:%S')}] {message}", flush=True)


def free_port() -> int:
    with socket.socket(socket.AF_INET, socket.SOCK_STREAM) as sock:
        sock.bind(("127.0.0.1", 0))
        return sock.getsockname()[1]


def _venv_python(venv: Path, *, windows: bool = os.name == "nt") -> Path:
    return venv / ("Scripts/python.exe" if windows else "bin/python")


def pid_alive(pid: int) -> bool:
    try:
        os.kill(pid, 0)
    except ProcessLookupError:
        return False
    except PermissionError:
        return True
    return True


class Client:
    """A keep-alive HTTP client; one per worker thread."""

    def __init__(self, port: int):
        self.port = port
        self.local = threading.local()

    def _connection(self) -> http.client.HTTPConnection:
        connection = getattr(self.local, "connection", None)
        if connection is None:
            connection = http.client.HTTPConnection("localhost", self.port, timeout=120)
            self.local.connection = connection
        return connection

    def request(self, method: str, path: str, body=None, content_type: str = "application/json") -> tuple[int, bytes]:
        headers = {}
        if body is not None:
            if not isinstance(body, (bytes, str)):
                body = json.dumps(body)
            headers["Content-Type"] = content_type
        for attempt in range(2):
            connection = self._connection()
            try:
                connection.request(method, path, body=body, headers=headers)
                response = connection.getresponse()
                return response.status, response.read()
            except (http.client.HTTPException, ConnectionError, OSError):
                connection.close()
                self.local.connection = None
                if attempt == 1:
                    raise
        raise AssertionError("unreachable")

    def expect(self, method: str, path: str, status: int, body=None, content_type: str = "application/json"):
        actual, payload = self.request(method, path, body, content_type)
        if actual != status:
            raise TrainingError(f"{method} {path} returned {actual}, expected {status}: {payload[:300]!r}")
        if payload and actual in (200, 201):
            try:
                return json.loads(payload)
            except ValueError:
                return payload.decode("utf-8", "replace")
        return None


class Workload:
    """The runtime scenarios: Netty HTTP, JSON serde, validation and Micronaut Data on H2."""

    def __init__(self, scale: float, has_summary: bool):
        self.scale = scale
        self.has_summary = has_summary
        self.random = random.Random(42)

    def count(self, base: int) -> int:
        return max(1, int(base * self.scale))

    def run(self, client: Client) -> dict:
        timings = {}
        for concurrency in (1, 8):
            start = time.monotonic()
            self._phase(client, concurrency)
            timings[f"concurrency-{concurrency}"] = round(time.monotonic() - start, 1)
        return timings

    def _parallel(self, concurrency: int, count: int, action) -> list:
        if concurrency == 1:
            return [action(i) for i in range(count)]
        with ThreadPoolExecutor(max_workers=concurrency) as pool:
            return list(pool.map(action, range(count)))

    def _pet(self, i: int) -> dict:
        return {
            "name": f"{NAMES[i % len(NAMES)]} {i}",
            "species": SPECIES[i % len(SPECIES)],
            "age": i % 17,
            "vaccinated": i % 3 == 0,
        }

    def _phase(self, client: Client, concurrency: int) -> None:
        self._parallel(concurrency, self.count(3000), lambda i: client.expect("GET", "/hello", 200))
        created = self._parallel(concurrency, self.count(1500), lambda i: client.expect("POST", "/pets", 201, self._pet(i)))
        ids = [pet["id"] for pet in created]

        def read(i: int) -> None:
            kind = i % 5
            if kind == 0:
                client.expect("GET", f"/pets/{ids[i % len(ids)]}", 200)
            elif kind == 1:
                client.expect("GET", f"/pets/species/{SPECIES[i % len(SPECIES)]}", 200)
            elif kind == 2:
                client.expect("GET", f"/pets/search/{NAMES[i % len(NAMES)]}", 200)
            elif kind == 3:
                client.expect("GET", f"/pets/count/{SPECIES[i % len(SPECIES)]}", 200)
            elif i % 50 == 4:
                client.expect("GET", "/pets", 200)
            else:
                client.expect("GET", f"/pets/{ids[-1 - i % len(ids)]}", 200)

        self._parallel(concurrency, self.count(3000), read)
        update_count = min(len(ids), self.count(600))
        self._parallel(concurrency, update_count, lambda i: client.expect(
            "PUT", f"/pets/{ids[i]}", 200, dict(self._pet(i + 7), name=f"Updated {i}")))

        def errors(i: int) -> None:
            kind = i % 4
            if kind == 0:
                client.expect("POST", "/pets", 400, {"name": "", "species": "", "age": -1})
            elif kind == 1:
                client.expect("GET", "/pets/999999999", 404)
            elif kind == 2:
                client.expect("POST", "/pets", 400, "{not json")
            else:
                client.expect("DELETE", "/pets/999999999", 404)

        self._parallel(concurrency, self.count(300), errors)
        if self.has_summary:
            small = self._summary_document(20, 40)
            self._parallel(concurrency, self.count(1500), lambda i: client.expect(
                "POST", "/pets/summary", 200, small, "text/plain"))
            large = self._summary_document(1500, 20000)
            self._parallel(concurrency, self.count(100), lambda i: client.expect(
                "POST", "/pets/summary", 200, large, "text/plain"))
        delete_count = min(len(ids), self.count(1500))
        self._parallel(concurrency, delete_count, lambda i: client.expect("DELETE", f"/pets/{ids[i]}", 204))

    def _summary_document(self, visits: int, words: int) -> str:
        vocabulary = ("fed", "walked", "groomed", "vaccinated", "weighed", "checked", "played", "slept")
        notes = " ".join(vocabulary[self.random.randrange(len(vocabulary))] for _ in range(words))
        return json.dumps({
            "notes": notes,
            "visits": [
                {"pet": NAMES[i % len(NAMES)], "when": f"2026-{1 + i % 12:02d}-{1 + i % 28:02d}T{i % 24:02d}:00:00", "cost": 10 + i % 90}
                for i in range(visits)
            ],
        })


class Trainer:

    def __init__(self, options: argparse.Namespace):
        self.options = options
        self.image: str = options.image
        self.jvm: bool = options.jvm
        self.work = Path(options.work_dir).resolve()
        self.apps = Path(options.apps_dir).resolve()
        self.profiles = Path(options.profiles_dir).resolve()
        self.pids = self.work / "pids"
        self.logs = self.work / "logs"
        self.shims = self.work / "shims"
        self.tools = dict(entry.split("=", 1) for entry in options.tool)
        self.summary: dict = {"image": self.image, "mode": "jvm" if self.jvm else "native", "scenarios": {}}

    # ---- setup ---------------------------------------------------------------------------------

    def prepare(self) -> None:
        if self.work.exists():
            shutil.rmtree(self.work)
        for directory in (self.work, self.pids, self.logs, self.shims):
            directory.mkdir(parents=True)
        if not self.jvm:
            if self.profiles.exists():
                shutil.rmtree(self.profiles)
            self.profiles.mkdir(parents=True)
            self._check_instrumented_executable()
            self._write_instrumented_shim()
        if self.image != "pyronaut-dev" or self.jvm:
            self._write_jvm_dev_shim()
        self.venv = self._create_venv()

    def _check_instrumented_executable(self) -> None:
        executable = Path(self.options.executable)
        if not executable.is_file():
            raise TrainingError(f"Missing instrumented {self.image}: {executable}. Build it with -Ppyronaut.pgo=instrument.")
        marker = Path(self.options.instrumented_marker)
        if not marker.is_file():
            raise TrainingError(f"{executable} was not built with -Ppyronaut.pgo=instrument (missing {marker})")
        recorded_path, recorded_size, recorded_mtime = marker.read_text().split()[:3]
        current = executable.stat()
        if Path(recorded_path) != executable.resolve() or int(recorded_size) != current.st_size \
                or int(recorded_mtime) // 1000 != int(current.st_mtime):
            raise TrainingError(f"{executable} changed after the instrumented build. Rebuild it with -Ppyronaut.pgo=instrument.")

    def _write_instrumented_shim(self) -> None:
        directory = self.shims / self.image
        directory.mkdir()
        executable = str(Path(self.options.executable).resolve())
        if os.name == "nt":
            shim = self._write_windows_shim(
                directory / self.image,
                WINDOWS_INSTRUMENTED_SHIM.replace("@EXECUTABLE@", repr(executable)),
            )
        else:
            shim = directory / self.image
            shim.write_text(INSTRUMENTED_SHIM.replace("@EXECUTABLE@", executable))
            shim.chmod(shim.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        self._copy_manifests(directory, Path(self.options.manifests_dir))
        if self.image == "pyronaut-dev":
            shutil.copytree(Path(self.options.dev_install_dir).resolve() / "lib", directory / "lib")
        self.instrumented_shim = shim

    def _write_windows_shim(self, base: Path, script: str) -> Path:
        helper = base.with_suffix(".py")
        shim = base.with_suffix(".cmd")
        helper.write_text(script, encoding="utf-8")
        shim.write_text(
            f'@echo off\r\n"{self.options.graalpy}" "%~dpn0.py" %*\r\nexit /b %ERRORLEVEL%\r\n',
            encoding="utf-8",
        )
        return shim

    def _write_jvm_dev_shim(self) -> None:
        install = Path(self.options.dev_install_dir).resolve()
        directory = self.shims / "jvm-dev"
        (directory / "bin").mkdir(parents=True)
        shutil.copytree(install / "lib", directory / "lib")
        base = directory / "bin" / "pyronaut-dev"
        if os.name == "nt":
            classpath = str(install / "lib" / "*")
            script = WINDOWS_JVM_DEV_SHIM.replace("@JAVA@", repr(str(Path(self.options.java_home) / "bin" / "java.exe")))
            script = script.replace("@CLASSPATH@", repr(classpath))
            shim = self._write_windows_shim(base, script)
        else:
            shim = base
            shim.write_text(JVM_DEV_SHIM.replace("@LIB@", str(install / "lib")))
            shim.chmod(shim.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
        self._copy_manifests(directory / "bin", install / "bin")
        self.jvm_dev_shim = shim

    @staticmethod
    def _copy_manifests(directory: Path, source: Path) -> None:
        for name in ("native-compile-classpath.txt", "native-provided-classpath.txt"):
            target = source / name
            if not target.is_file():
                raise TrainingError(f"Missing classpath manifest {target}")
            shutil.copyfile(target, directory / name)

    def _create_venv(self) -> Path:
        venv = self.work / "venv"
        self._check([self.options.graalpy, "-m", "venv", str(venv)], "create-venv", cwd=self.work, env=os.environ.copy())
        python = _venv_python(venv)
        self._check([str(python), "-m", "pip", "install", "--quiet", "pytest==9.0.3"],
                    "pip-install", cwd=self.work, env=os.environ.copy())
        return venv

    def copy_app(self, name: str, port: int | None = None) -> Path:
        source = self.apps / name
        target = self.work / "apps" / name
        shutil.copytree(source, target)
        pyproject = target / "pyproject.toml"
        if pyproject.is_file():
            content = pyproject.read_text().replace("@REPOSITORY@", str(Path(self.options.repository).resolve()))
            toolchain = "jvm" if self.jvm else "native"
            pyproject.write_text(content + f"\n[tool.pyronaut.toolchain]\ntype = '{toolchain}'\n")
        if port is not None:
            self.set_port(target, port)
        return target

    @staticmethod
    def set_port(app: Path, port: int) -> None:
        # Pyronaut apps keep their configuration in config/, Maven apps in src/main/resources/.
        config = next(path for path in (app / "config" / "application.toml",
                                        app / "src" / "main" / "resources" / "application.toml") if path.is_file())
        config.write_text(config.read_text().replace("port = 8080", f"port = {port}", 1))

    def run_args(self, app: Path) -> list[str]:
        """``pyronaut run`` arguments. A Maven app has no pyproject.toml toolchain, so JVM runs select it here."""
        return ["run", "--no-validate", *(["--jvm"] if self.jvm and (app / "pom.xml").is_file() else [])]

    # ---- process control -----------------------------------------------------------------------

    def env(self, scenario: str) -> dict:
        env = os.environ.copy()
        env.pop("GRAALVM_QUICK_BUILD", None)
        env.pop("MICRONAUT_GHT", None)
        env.update({
            "JAVA_HOME": self.options.java_home,
            "PYTHONPATH": self.options.cli_source,
            "PYRONAUT_TRACE_DELEGATION": "1",
            "VIRTUAL_ENV": str(self.venv),
            "PATH": f"{_venv_python(self.venv).parent}{os.pathsep}{Path(self.options.java_home) / 'bin'}{os.pathsep}{env.get('PATH', '')}",
            "PGO_SCENARIO": scenario,
            "PGO_PROFILES_DIR": str(self.profiles),
            "PGO_PIDS_DIR": str(self.pids),
        })
        for tool, executable in self.tools.items():
            env[f"PYRONAUT_{tool.upper().replace('-', '_')}_EXECUTABLE"] = executable
        if self.jvm:
            env["PYRONAUT_DEV_NATIVE_EXECUTABLE"] = str(self.jvm_dev_shim)
            return env
        native_key = f"{self.image.upper().replace('-', '_')}_NATIVE_EXECUTABLE"
        env[native_key] = str(self.instrumented_shim)
        if self.image != "pyronaut-dev":
            env["PYRONAUT_DEV_NATIVE_EXECUTABLE"] = str(self.jvm_dev_shim)
        return env

    def cli(self, *args: str) -> list[str]:
        return [self.options.graalpy, "-m", "pyronaut_cli_v2", *args]

    def _check(self, command: list[str], scenario: str, cwd: Path, env: dict | None = None) -> float:
        log_file = self.logs / f"{scenario}.log"
        start = time.monotonic()
        with log_file.open("a") as output:
            output.write("$ " + " ".join(command) + "\n")
            output.flush()
            result = subprocess.run(command, cwd=cwd, env=env if env is not None else self.env(scenario),
                                    stdout=output, stderr=subprocess.STDOUT)
        if result.returncode != 0:
            raise TrainingError(f"{scenario}: {' '.join(command[2:])} exited with {result.returncode}; see {log_file}\n"
                                + self._log_contents(log_file))
        return round(time.monotonic() - start, 1)

    @staticmethod
    def _log_contents(path: Path) -> str:
        return path.read_text(errors="replace").rstrip()

    def skipped(self, scenario: str) -> bool:
        if scenario in self.options.skip:
            log(f"{scenario}: skipped")
            self.summary["scenarios"][scenario] = {"skipped": True}
            return True
        return False

    def command(self, scenario: str, cwd: Path, *args: str) -> None:
        if self.skipped(scenario):
            return
        log(f"{scenario}: pyronaut {' '.join(args)}")
        seconds = self._check(self.cli(*args), scenario, cwd)
        self._record(scenario, seconds=seconds)

    def serve(self, scenario: str, cwd: Path, args: list[str], port: int, workload: Workload | None,
              launches: int = 1) -> None:
        if self.skipped(scenario):
            return
        for launch in range(launches):
            name = scenario if launches == 1 else f"{scenario}-{launch + 1}"
            log(f"{name}: pyronaut {' '.join(args)} (port {port})")
            log_file = self.logs / f"{name}.log"
            output = log_file.open("w")
            started = time.monotonic()
            process = subprocess.Popen(self.cli(*args), cwd=cwd, env=self.env(name), stdout=output,
                                       stderr=subprocess.STDOUT, **_process_group_options())
            details: dict = {}
            try:
                self._wait_ready(port, process, log_file)
                details["ready-seconds"] = round(time.monotonic() - started, 1)
                client = Client(port)
                if workload is None:
                    client.expect("GET", "/hello", 200)
                else:
                    details["workload-seconds"] = workload.run(client)
            finally:
                self._stop(name, process)
                output.close()
            self._record(name, **details)

    def _wait_ready(self, port: int, process: subprocess.Popen, log_file: Path) -> None:
        deadline = time.monotonic() + self.options.startup_timeout
        while time.monotonic() < deadline:
            if process.poll() is not None:
                raise TrainingError(f"Server exited with {process.returncode} before it was ready; see {log_file}\n"
                                    + self._log_contents(log_file))
            try:
                connection = http.client.HTTPConnection("localhost", port, timeout=5)
                connection.request("GET", "/hello")
                if connection.getresponse().status == 200:
                    return
            except OSError:
                pass
            time.sleep(0.5)
        raise TrainingError(f"Server on port {port} was not ready after {self.options.startup_timeout}s; see {log_file}")

    def _stop(self, scenario: str, process: subprocess.Popen) -> None:
        if self.jvm:
            if os.name == "nt":
                self._stop_windows_children(scenario)
            self._signal_group(process, signal.SIGTERM)
            return
        # Stop the CLI first so that a development watcher cannot restart the application, then
        # stop the launcher with SIGTERM so that it writes its profile.
        if process.poll() is None:
            process.kill()
            process.wait()
        if os.name == "nt":
            self._stop_windows_children(scenario)
            return
        for pid in self._pids(scenario):
            if pid_alive(pid):
                os.kill(pid, signal.SIGTERM)
        deadline = time.monotonic() + self.options.shutdown_timeout
        while time.monotonic() < deadline and any(pid_alive(pid) for pid in self._pids(scenario)):
            time.sleep(0.5)
        survivors = [pid for pid in self._pids(scenario) if pid_alive(pid)]
        for pid in survivors:
            os.kill(pid, signal.SIGKILL)
        self._signal_group(process, signal.SIGKILL)
        if survivors:
            raise TrainingError(f"{scenario}: launcher processes {survivors} ignored SIGTERM and were killed")

    def _stop_windows_children(self, scenario: str) -> None:
        pids = self._pids(scenario)
        for pid in pids:
            if pid_alive(pid):
                try:
                    os.kill(pid, signal.CTRL_BREAK_EVENT)
                except (ProcessLookupError, PermissionError):
                    pass
        deadline = time.monotonic() + self.options.shutdown_timeout
        while time.monotonic() < deadline and any(pid_alive(pid) for pid in pids):
            time.sleep(0.5)
        survivors = [pid for pid in pids if pid_alive(pid)]
        for pid in survivors:
            os.kill(pid, signal.SIGTERM)
        if survivors:
            raise TrainingError(f"{scenario}: launcher processes {survivors} ignored CTRL_BREAK and were terminated")

    @staticmethod
    def _signal_group(process: subprocess.Popen, sig: int) -> None:
        if os.name == "nt":
            if process.poll() is None:
                process.send_signal(signal.CTRL_BREAK_EVENT)
            try:
                process.wait(timeout=60)
            except subprocess.TimeoutExpired:
                process.kill()
                process.wait()
            return
        try:
            os.killpg(process.pid, sig)
        except (ProcessLookupError, PermissionError):
            pass
        try:
            process.wait(timeout=60)
        except subprocess.TimeoutExpired:
            os.killpg(process.pid, signal.SIGKILL)
            process.wait()

    def _pids(self, scenario: str) -> list[int]:
        files = (self.pids / f"{scenario}.pids", self.pids / f"{scenario}.children.pids")
        return list(dict.fromkeys(
            int(line.split("\t", 1)[0])
            for file in files if file.is_file()
            for line in file.read_text().splitlines() if line.strip()
        ))

    def _launcher_profiles(self, scenario: str) -> list[tuple[int, Path]]:
        file = self.pids / f"{scenario}.pids"
        if not file.is_file():
            return []
        entries = []
        for line in file.read_text().splitlines():
            if not line.strip():
                continue
            pid, separator, profile = line.partition("\t")
            profile_path = self.profiles / profile if separator else self.profiles / f"{scenario}-{pid}.iprof"
            entries.append((int(pid), profile_path))
        return entries

    def _record(self, scenario: str, **details) -> None:
        entry = dict(details)
        if not self.jvm:
            profiles = sorted(self.profiles.glob(f"{scenario}-*.iprof"))
            launched = self._launcher_profiles(scenario)
            missing = [str(profile) for _pid, profile in launched if not profile.is_file()]
            empty = [profile.name for profile in profiles if profile.stat().st_size == 0]
            if not launched:
                raise TrainingError(f"{scenario}: the instrumented {self.image} was never launched")
            if missing or empty:
                raise TrainingError(f"{scenario}: no profile written by launcher processes {missing or empty}")
            entry["profiles"] = {profile.name: profile.stat().st_size for profile in profiles}
        self.summary["scenarios"][scenario] = entry

    # ---- scenarios -----------------------------------------------------------------------------

    def train(self) -> None:
        if self.image == "pyronaut-dev":
            self._train_dev()
        elif self.image == "pyronaut-run-python":
            self._train_runtime("python", has_summary=True)
        else:
            # A plain Maven project run through Pyronaut's external build support: its runtime classpath is
            # what Maven resolves, without the GraalPy runtime a pyproject.toml project always gets.
            self._train_runtime(RUN_APP, has_summary=True)

    def _train_runtime(self, app_name: str, has_summary: bool) -> None:
        port = free_port()
        app = self.copy_app(app_name, port)
        # Preparing the application is not part of this image's training.
        prepare_env = self.env("prepare")
        if not self.jvm:
            prepare_env.pop(f"{self.image.upper().replace('-', '_')}_NATIVE_EXECUTABLE")
        for args in (("install",), ("process",)):
            log(f"prepare: pyronaut {' '.join(args)}")
            self._check(self.cli(*args), "prepare", app, env=prepare_env)
        run = self.run_args(app)
        self.serve("startup", app, run, port, None, launches=self.options.startup_launches)
        self.serve("runtime", app, run, port, Workload(self.options.scale, has_summary))

    def _train_dev(self) -> None:
        port = free_port()
        app = self.copy_app("python", port)
        self.command("install", app, "install")
        self.command("process-clean", app, "process")
        controller = app / "src" / "training" / "controller.py"
        controller.write_text(controller.read_text() + "\n\n# Changed by the training driver to exercise incremental processing.\n")
        self.command("process-incremental", app, "process")
        model = app / "src" / "training" / "hello.py"
        model.write_text(model.read_text() + '\n\n@Get(value="/hello/{name}", produces="text/plain")\n'
                         'def hello_name(name: str) -> str:\n    return f"Hello {name}"\n')
        self.command("process-incremental-new-route", app, "process")
        self.command("test", app, "test")
        self.serve("dev-run", app, ["dev", "--no-validate"], port,
                   Workload(self.options.scale, has_summary=True))

        java_app = self.copy_app("java", free_port())
        self.command("install-java", java_app, "install")
        self.command("process-java", java_app, "process")

        direct_python = self.copy_app("direct-python")
        direct_port = free_port()
        self.serve("direct-python", direct_python, ["run", "app.py", "--port", str(direct_port)], direct_port,
                   Workload(self.options.scale / 2, has_summary=False))
        direct_java = self.copy_app("direct-java")
        direct_port = free_port()
        self.serve("direct-java", direct_java, ["run", "App.java", "--port", str(direct_port)], direct_port,
                   Workload(self.options.scale / 2, has_summary=False))


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("--image", choices=IMAGES, required=True)
    parser.add_argument("--jvm", action="store_true", help="run the scenarios on the JVM launchers without collecting profiles")
    parser.add_argument("--executable", help="the instrumented native executable")
    parser.add_argument("--instrumented-marker", help="instrumented-executable.txt written by the instrumented build")
    parser.add_argument("--manifests-dir", help="directory holding the image's native-*-classpath.txt manifests")
    parser.add_argument("--dev-install-dir", required=True, help="the pyronaut-dev installDist directory")
    parser.add_argument("--profiles-dir", required=True)
    parser.add_argument("--work-dir", required=True)
    parser.add_argument("--apps-dir", required=True)
    parser.add_argument("--repository", required=True, help="staged repository with the Pyronaut test artifacts")
    parser.add_argument("--cli-source", required=True, help="pyronaut/src/main/python")
    parser.add_argument("--graalpy", required=True)
    parser.add_argument("--java-home", required=True)
    parser.add_argument("--tool", action="append", default=[], help="<tool>=<JVM launcher>, e.g. install=/path/bin/pyronaut-install")
    parser.add_argument("--scale", type=float, default=1.0, help="multiplies the number of requests")
    parser.add_argument("--skip", action="append", default=[], help="scenario to skip; for local debugging only")
    parser.add_argument("--startup-launches", type=int, default=5)
    parser.add_argument("--startup-timeout", type=int, default=600)
    parser.add_argument("--shutdown-timeout", type=int, default=300)
    options = parser.parse_args(argv)
    if not options.jvm and not (options.executable and options.instrumented_marker and options.manifests_dir):
        parser.error("--executable, --instrumented-marker and --manifests-dir are required unless --jvm is given")
    return options


def main(argv: list[str]) -> int:
    options = parse_args(argv)
    trainer = Trainer(options)
    started = time.monotonic()
    try:
        trainer.prepare()
        trainer.train()
    except TrainingError as error:
        log(f"FAILED: {error}")
        return 1
    trainer.summary["seconds"] = round(time.monotonic() - started, 1)
    summary_file = Path(options.work_dir) / "training-summary.json"
    summary_file.write_text(json.dumps(trainer.summary, indent=2) + "\n")
    log(f"done in {trainer.summary['seconds']}s; summary: {summary_file}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
