Pyronaut exposes the entirety of the https://docs.micronaut.io/latest/[Micronaut API] to Python by representing any Java annotation as a Python decorator at the source level.

This means you can use any documented Micronaut construct in Python code.

For example controllers are defined with Python decorators that bridge to Micronaut's annotations used in other languages like Java, Kotlin and Groovy:

.Using HTTP decorators
[source,python]
----
from micronaut.http.annotation import Get


@Get(value="/", produces="text/plain")
def index() -> str:
    return "Hello from Pyronaut"
----

One caveat is that the packages you import start with `micronaut` instead of `io.micronaut` so when refering to the https://docs.micronaut.io/latest/api/[API Reference] you need to omit the `io.` on any import declaration. This wrinkle is due to the fact Python itself forbids defining packages that are part of the core Python API and since `io` is a core Python package this would otherwise conflict and produce a runtime error.

This flexibility to use any Java side annotation as a Python decorator means you can leverage advanced features of Micronaut such as Micronaut serialization to define JSON mapping using Jackson:

.Writing Serializable data classes
[source, python]
----
from dataclasses import dataclass
from typing import Annotated

from jakarta.validation.constraints import NotBlank, Pattern, Size
from micronaut.serde.annotation import Serdeable
from com.fasterxml.jackson.annotation import JsonProperty

@Serdeable # (1)
@dataclass
class Person:
    """Create/update form for Owner."""

    name: Annotated[str, NotBlank, Size(min=1, max=30)] # (2) 
    telephone: Annotated[str | None, NotBlank, Pattern(regexp=r"\d{10}", message="Telephone must be a 10-digit number")] = None
    age: Annotated[int, JsonProperty("person_age")] # (3)
----

<1> Here the `@Serdeable` decorator is used to indicate that the data class can be serialized and deserialized
<2> The `name` attribute has some `jakarta.validation` constraints applied to it via decorators
<3> The `age` attribute is mapped to a different JSON attribute name ("person_age") using `JsonProperty`


So what happens is during the execution of `pyronaut process` which is executed prior to running the application Micronaut at build time produces additional artefacts during this processing step that know how to serialization and deserialization the `Person` data class plus some code that bridges that enable Python <--> Java interop.

Any Java API can be imported and used directly from Python and advanced features like https://docs.micronaut.io/latest/validation/[Micronaut Validation], https://docs.micronaut.io/latest/serde/[Micronaut Serialization] and https://docs.micronaut.io/latest/data[Micronaut Data] "just work" in the context of Python enabling a highly productive, scalable and portable development platform for Python developers.

A Pyronaut decorator can be used at the type or function level using the regular decorator syntax (for example `@Get`). 

Named arguments can be used used with decorators which are map to the underlying Java annotation values (for example `@Get(value="/", produces="text/plain")`).

The standard `typing.Annotated` Python construct can be use to apply Pyronaut decorators to class attributes or function arguments (for example `Annotated[str, NotBlank, Size(min=1, max=30)]`).

For more information checkout the https://docs.micronaut.io/latest/core/#core-introduction[Micronaut core documentation] which has been updated with Python examples and a dedicated https://docs.micronaut.io/latest/core/#core-python[Python Section] cover features specific to Python such as async/await support. 