= Introduction

Pyronaut provides a batteries-included framework for building Cloud ready Python applications based GraalPy, Micronaut and GraalVM.

By running on the JVM or GraalVM Native Image, Pyronaut provides a solid, highly scalable foundation for Python applications that are easily observable, manageable and portable across operation systems.

Pyronaut is built to scale from executable Python modules to larger projects that require more structure.

The simplest Pyronaut application can be defined in a single Python module:

.Pyronaut `app.py`
[source,python]
----
from micronaut.http.annotation import Get

@Get("/")
def index() -> dict[str, str]:
    return {"Hello": "World"}
----

And executed with `pyronaut run app.py`.

Pyronaut surfaces all Micronaut features to the Python developer through decorators that enable advanced features like dependency injection, validation, serialization, data access, integration testing and more.

Any Java side annotation can be represented in Python source code as a decorator enabling access to the entire Mironaut Platform API.

The `pyronaut` command is the main entry point.

Project configuration can be defined in `pyproject.toml`, the `pyronaut` command then uses this configuration to enable processing of Python and Java source code, testing with pytest or JUnit 5 and building production deployable artefacts like wheels, docker images etc.

Typical Pyronaut projects contain:

- Python application sources under `src`
- Python tests under `tests`
- Micronaut configuration under `config`
- Python and/or Java dependencies declared in `pyproject.toml`
- Generated Pyronaut state under `__pyronaut__`

IDE integration with Pylance and/or PyCharm is included out of the box with the `pyronaut install` command producing IDE-ready stubs that enable code completion in the user project.