import static io.micronaut.build.TestFramework.JUNIT6

plugins {
    id 'io.micronaut.build.internal.pyronaut-base'
    id "io.micronaut.build.internal.module"
}
micronautBuild {
    descriptor {
        parentModuleId = "io.micronaut.pyronaut:micronaut-pyronaut"
    }
    testFramework = JUNIT6
    binaryCompatibility {
        enabledAfter "1.0.0"
    }
}

repositories {
    mavenLocal()
}

tasks.withType(Checkstyle).configureEach {
    exclude {
        it.toString().contains('generated')
    }
}
