pluginManagement {
    repositories {
        // Allow resolving development plugins from the local Maven cache (for j2pyi plugin).
        mavenLocal()
        gradlePluginPortal()
        mavenCentral()
    }
}

plugins {
    id 'io.micronaut.build.shared.settings' version '8.0.0-M13'
}

rootProject.name = 'pyronaut-parent'

include 'pyronaut-projectgen'
include 'pyronaut-projectgen-app'
include 'pyronaut-bom'
// New module that generates Python .pyi stubs for the Micronaut API surface
include 'pyronaut-api'

enableFeaturePreview 'TYPESAFE_PROJECT_ACCESSORS'

micronautBuild {
    useStandardizedProjectNames=true
    importMicronautCatalog()
    importMicronautCatalog("micronaut-serde")
    importMicronautCatalog("micronaut-views")
    importMicronautCatalog("micronaut-validation")
}
