package io.micronaut.pyronaut.install;

import io.micronaut.pyronaut.config.model.PyprojectModelReader;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class DependencyLockTest {
    @TempDir
    Path tempDir;

    private String previousMavenRepoLocal;
    private String previousIdeStubsCache;

    @BeforeEach
    void isolateRepositories() {
        previousMavenRepoLocal = System.getProperty("maven.repo.local");
        previousIdeStubsCache = System.getProperty("pyronaut.ide-stubs.cache-dir");
        System.setProperty("maven.repo.local", tempDir.resolve("maven-local").toString());
        System.setProperty("pyronaut.ide-stubs.cache-dir", tempDir.resolve("ide-stubs").toString());
    }

    @AfterEach
    void restoreRepositories() {
        restore("maven.repo.local", previousMavenRepoLocal);
        restore("pyronaut.ide-stubs.cache-dir", previousIdeStubsCache);
        DependencyLock.activate(null);
    }

    @Test
    void rendersSortedEntriesThatReadBack() throws IOException {
        DependencyLock.Entry b = entry("org/b/b/1.0/b-1.0.jar", "b");
        DependencyLock.Entry a = entry("org/a/a/1.0/a-1.0.pom", "a");
        Path file = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(file, DependencyLock.render(List.of(b, a)));

        String rendered = Files.readString(file);
        assertTrue(rendered.startsWith("# This file is generated by `pyronaut lock`."));
        assertTrue(rendered.indexOf("org/a/a") < rendered.indexOf("org/b/b"), rendered);
        assertEquals(List.of(a, b), DependencyLock.read(file));
    }

    @Test
    void rejectsUnsupportedOrUnsafeLockFiles() throws IOException {
        Path file = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(file, "version = 2\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("format version"));

        Files.writeString(file, DependencyLock.render(List.of(entry("../escape/x-1.jar", "x"))));
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("must be relative"));

        Files.writeString(file, "version = 1\n[[artifact]]\npath = \"a/b/1/b-1.jar\"\nsha256 = \"abc\"\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("not a SHA-256"));
    }

    @Test
    void lockedModeRequiresALockFile() throws IOException {
        IllegalArgumentException failure = assertThrows(IllegalArgumentException.class,
            () -> DependencyLock.open(tempDir.resolve(DependencyLock.FILE_NAME), false, true, null));
        assertTrue(failure.getMessage().contains("pyronaut lock"));
        assertEquals(DependencyLock.Mode.OFF,
            DependencyLock.open(tempDir.resolve(DependencyLock.FILE_NAME), false, false, null).mode());
    }

    @Test
    void writesLockWithJarsPomsRepositoryAndChecksums() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);

        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        List<DependencyLock.Entry> entries = DependencyLock.read(lockFile);
        assertEquals(List.of(
            "com/example/app/1.0/app-1.0.jar",
            "com/example/app/1.0/app-1.0.pom",
            "com/example/dep/2.0/dep-2.0.jar",
            "com/example/dep/2.0/dep-2.0.pom"
        ), entries.stream().map(DependencyLock.Entry::path).toList());
        String repositoryUrl = repository.toUri().toString();
        for (DependencyLock.Entry entry : entries) {
            assertEquals(repositoryUrl, entry.repository());
            assertEquals(repositoryUrl + entry.path(), entry.url());
            assertEquals(DependencyLock.sha256(repository.resolve(entry.path())), entry.sha256());
        }
        assertEquals("com.example:dep:jar:2.0", entries.get(2).coordinates());

        // A second run records the same lock, also from the populated local repository.
        String first = Files.readString(lockFile);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));
        assertEquals(first, Files.readString(lockFile));
    }

    @Test
    void failsWhenALockedChecksumDoesNotMatch() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        String tampered = Files.readString(lockFile).replace(
            DependencyLock.sha256(repository.resolve("com/example/dep/2.0/dep-2.0.jar")),
            "0".repeat(64)
        );
        Files.writeString(lockFile, tampered);

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> command.localRepository = tempDir.resolve("fresh-local")));

        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        String message = errors.toString(StandardCharsets.UTF_8);
        assertTrue(message.contains("com.example:dep:jar:2.0 does not match pyronaut.lock"), message);
        assertTrue(message.contains("run `pyronaut lock`"), message);
    }

    @Test
    void lockedModeRejectsArtifactsMissingFromTheLock() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        List<DependencyLock.Entry> withoutDep = DependencyLock.read(lockFile).stream()
            .filter(entry -> !entry.path().equals("com/example/dep/2.0/dep-2.0.jar"))
            .toList();
        Files.writeString(lockFile, DependencyLock.render(withoutDep));

        // Without --locked an unlisted artifact is accepted.
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> { }));

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> command.locked = true));
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("com.example:dep:jar:2.0 is not in pyronaut.lock"));
    }

    @Test
    void lockRepositoryResolvesOfflineFromLockedArtifactsOnly() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        // Lay out the locked artifacts the way a Nix or air-gapped build would,
        // fetching each one by its path, then remove the original repository.
        Path lockRepository = tempDir.resolve("lock-repository");
        for (DependencyLock.Entry entry : DependencyLock.read(project.resolve(DependencyLock.FILE_NAME))) {
            Path target = lockRepository.resolve(entry.path());
            Files.createDirectories(target.getParent());
            Files.copy(repository.resolve(entry.path()), target);
        }
        deleteRecursively(repository);

        Path freshLocal = tempDir.resolve("offline-local");
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> {
            command.offline = true;
            command.localRepository = freshLocal;
            command.lockRepository = lockRepository;
        }));
        List<String> runtime = Files.readAllLines(project.resolve("__pyronaut__/resolved-runtime-dependencies"));
        assertTrue(runtime.contains(freshLocal.resolve("com/example/dep/2.0/dep-2.0.jar").toString()), runtime.toString());

        // An artifact the lock repository lacks fails resolution with a pointer to the lock.
        Files.delete(lockRepository.resolve("com/example/dep/2.0/dep-2.0.jar"));
        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> {
            command.offline = true;
            command.noCache = true;
            command.localRepository = tempDir.resolve("offline-local-2");
            command.lockRepository = lockRepository;
        }));
        assertEquals(InstallExitCode.RESOLUTION_ERROR.code(), exitCode);
        String message = errors.toString(StandardCharsets.UTF_8);
        assertTrue(message.contains("com.example:dep:jar:2.0"), message);
        assertTrue(message.contains("only uses the lock repository"), message);
    }

    @Test
    void lockModeIsReadFromTheEnvironment() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        Path lockFile = tempDir.resolve("elsewhere/custom.lock");
        Map<String, String> env = Map.of(DependencyLock.LOCK_FILE_ENV, lockFile.toString());
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> {
            command.writeLock = true;
            command.setEnvReader(env::get);
        }));
        assertTrue(Files.isRegularFile(lockFile));
        assertFalse(Files.exists(project.resolve(DependencyLock.FILE_NAME)));

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command ->
            command.setEnvReader(Map.of(DependencyLock.LOCKED_ENV, "true")::get)));
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("does not exist"));
    }

    private int install(Path project, CommandCustomizer customizer) throws Exception {
        PyronautInstallMain command = new PyronautInstallMain(
            new PyprojectModelReader(),
            new MavenClasspathResolver(),
            new PyprojectEditorSupport(),
            new PythonEditorSupport(),
            new ExternalBuildResolver(),
            (model, localRepository, offline, refresh, listener) -> null
        );
        command.projectDir = project;
        command.scope = "runtime";
        command.progress = "off";
        command.localRepository = tempDir.resolve("local");
        command.setEnvReader(name -> null);
        customizer.customize(command);
        return command.call();
    }

    private Path remoteRepository() throws IOException {
        Path repository = tempDir.resolve("remote");
        writeArtifact(repository, "com.example", "app", "1.0", "com.example:dep:2.0", new byte[]{1});
        writeArtifact(repository, "com.example", "dep", "2.0", null, new byte[]{2});
        return repository;
    }

    private Path project(Path repository) throws IOException {
        Path project = tempDir.resolve("project");
        Files.createDirectories(project);
        Files.writeString(project.resolve("pyproject.toml"), """
            [project]
            name = "lock-test"

            [tool.pyronaut]
            repositories = ["%s"]

            [tool.pyronaut.dependencies]
            runtime = ["com.example:app:1.0"]
            build = []
            test = []

            [tool.pyronaut.test-resources]
            enabled = false
            """.formatted(repository.toUri()));
        return project;
    }

    private static void writeArtifact(Path repository,
                                      String groupId,
                                      String artifactId,
                                      String version,
                                      String dependency,
                                      byte[] jar) throws IOException {
        Path directory = repository.resolve(groupId.replace('.', '/')).resolve(artifactId).resolve(version);
        Files.createDirectories(directory);
        String dependencies = "";
        if (dependency != null) {
            String[] parts = dependency.split(":");
            dependencies = """
                  <dependencies>
                    <dependency>
                      <groupId>%s</groupId>
                      <artifactId>%s</artifactId>
                      <version>%s</version>
                    </dependency>
                  </dependencies>
                """.formatted(parts[0], parts[1], parts[2]);
        }
        Files.writeString(directory.resolve(artifactId + "-" + version + ".pom"), """
            <project xmlns="http://maven.apache.org/POM/4.0.0">
              <modelVersion>4.0.0</modelVersion>
              <groupId>%s</groupId>
              <artifactId>%s</artifactId>
              <version>%s</version>
            %s</project>
            """.formatted(groupId, artifactId, version, dependencies));
        Files.write(directory.resolve(artifactId + "-" + version + ".jar"), jar);
    }

    private static DependencyLock.Entry entry(String path, String name) {
        return new DependencyLock.Entry("org." + name + ":" + name + ":jar:1.0", path,
            "https://repo.example/", "https://repo.example/" + path, name.repeat(64).substring(0, 64).replaceAll("[^a-f]", "a"));
    }

    private static int captureErrors(ByteArrayOutputStream errors, ExitCodeAction action) throws Exception {
        PrintStream previous = System.err;
        System.setErr(new PrintStream(errors, true, StandardCharsets.UTF_8));
        try {
            return action.run();
        } finally {
            System.setErr(previous);
        }
    }

    private static void deleteRecursively(Path directory) throws IOException {
        try (var paths = Files.walk(directory)) {
            for (Path path : paths.sorted(java.util.Comparator.reverseOrder()).toList()) {
                Files.delete(path);
            }
        }
    }

    private static void restore(String property, String value) {
        if (value == null) {
            System.clearProperty(property);
        } else {
            System.setProperty(property, value);
        }
    }

    @FunctionalInterface
    private interface CommandCustomizer {
        void customize(PyronautInstallMain command);
    }

    @FunctionalInterface
    private interface ExitCodeAction {
        int run() throws Exception;
    }
}
