package io.micronaut.pyronaut.install;

import io.micronaut.pyronaut.config.model.PyprojectModelException;
import io.micronaut.pyronaut.config.model.PyprojectModelReader;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.io.PrintStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

final class DependencyLockTest {
    @TempDir
    Path tempDir;

    private String previousMavenRepoLocal;
    private String previousIdeStubsCache;

    @BeforeEach
    void isolateRepositories() {
        previousMavenRepoLocal = System.getProperty("maven.repo.local");
        previousIdeStubsCache = System.getProperty("pyronaut.ide-stubs.cache-dir");
        System.setProperty("maven.repo.local", tempDir.resolve("maven-local").toString());
        System.setProperty("pyronaut.ide-stubs.cache-dir", tempDir.resolve("ide-stubs").toString());
    }

    @AfterEach
    void restoreRepositories() {
        restore("maven.repo.local", previousMavenRepoLocal);
        restore("pyronaut.ide-stubs.cache-dir", previousIdeStubsCache);
        DependencyLock.activate(null);
    }

    @Test
    void rendersSortedEntriesThatReadBack() throws IOException {
        DependencyLock.Entry b = entry("org/b/b/1.0/b-1.0.jar", "b");
        DependencyLock.Entry a = entry("org/a/a/1.0/a-1.0.pom", "a");
        Path file = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(file, DependencyLock.render(List.of(b, a)));

        String rendered = Files.readString(file);
        assertTrue(rendered.startsWith("# This file is generated by `pyronaut lock`."));
        assertTrue(rendered.indexOf("org/a/a") < rendered.indexOf("org/b/b"), rendered);
        assertEquals(List.of(a, b), DependencyLock.read(file));
    }

    @Test
    void rejectsUnsupportedOrUnsafeLockFiles() throws IOException {
        Path file = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(file, "version = 2\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("format version"));

        Files.writeString(file, DependencyLock.render(List.of(entry("../escape/x-1.jar", "x"))));
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("must be relative"));

        Files.writeString(file, "version = 1\n[[artifact]]\npath = \"a/b/1/b-1.jar\"\nsha256 = \"abc\"\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("not a SHA-256"));
    }

    @Test
    void lockedModeRequiresALockFile() throws IOException {
        IllegalArgumentException failure = assertThrows(IllegalArgumentException.class,
            () -> DependencyLock.open(tempDir.resolve(DependencyLock.FILE_NAME), false, true, null));
        assertTrue(failure.getMessage().contains("pyronaut lock"));
        assertEquals(DependencyLock.Mode.OFF,
            DependencyLock.open(tempDir.resolve(DependencyLock.FILE_NAME), false, false, null).mode());
    }

    @Test
    void writesLockWithJarsPomsRepositoryAndChecksums() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);

        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        List<DependencyLock.Entry> entries = DependencyLock.read(lockFile);
        assertEquals(List.of(
            "com/example/app/1.0/app-1.0.jar",
            "com/example/app/1.0/app-1.0.pom",
            "com/example/dep/2.0/dep-2.0.jar",
            "com/example/dep/2.0/dep-2.0.pom"
        ), entries.stream().map(DependencyLock.Entry::path).toList());
        String repositoryUrl = repository.toUri().toString();
        for (DependencyLock.Entry entry : entries) {
            assertEquals(repositoryUrl, entry.repository());
            assertEquals(repositoryUrl + entry.path(), entry.url());
            assertEquals(DependencyLock.sha256(repository.resolve(entry.path())), entry.sha256());
        }
        assertEquals("com.example:dep:jar:2.0", entries.get(2).coordinates());

        // A second run records the same lock, also from the populated local repository.
        String first = Files.readString(lockFile);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));
        assertEquals(first, Files.readString(lockFile));
    }

    @Test
    void failsWhenALockedChecksumDoesNotMatch() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        String tampered = Files.readString(lockFile).replace(
            DependencyLock.sha256(repository.resolve("com/example/dep/2.0/dep-2.0.jar")),
            "0".repeat(64)
        );
        Files.writeString(lockFile, tampered);

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> command.localRepository = tempDir.resolve("fresh-local")));

        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        String message = errors.toString(StandardCharsets.UTF_8);
        assertTrue(message.contains("com.example:dep:jar:2.0 does not match pyronaut.lock"), message);
        assertTrue(message.contains("run `pyronaut lock`"), message);
    }

    @Test
    void lockedModeRejectsArtifactsMissingFromTheLock() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        List<DependencyLock.Entry> withoutDep = DependencyLock.read(lockFile).stream()
            .filter(entry -> !entry.path().equals("com/example/dep/2.0/dep-2.0.jar"))
            .toList();
        Files.writeString(lockFile, DependencyLock.render(withoutDep));

        // Without --locked an unlisted artifact is accepted.
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> { }));

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> command.locked = true));
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("com.example:dep:jar:2.0 is not in pyronaut.lock"));
    }

    @Test
    void lockRepositoryResolvesOfflineFromLockedArtifactsOnly() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        // Lay out the locked artifacts the way a Nix or air-gapped build would,
        // fetching each one by its path, then remove the original repository.
        Path lockRepository = tempDir.resolve("lock-repository");
        for (DependencyLock.Entry entry : DependencyLock.read(project.resolve(DependencyLock.FILE_NAME))) {
            Path target = lockRepository.resolve(entry.path());
            Files.createDirectories(target.getParent());
            Files.copy(repository.resolve(entry.path()), target);
        }
        deleteRecursively(repository);

        Path freshLocal = tempDir.resolve("offline-local");
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> {
            command.offline = true;
            command.localRepository = freshLocal;
            command.lockRepository = lockRepository;
        }));
        List<String> runtime = Files.readAllLines(project.resolve("__pyronaut__/resolved-runtime-dependencies"));
        assertTrue(runtime.contains(freshLocal.resolve("com/example/dep/2.0/dep-2.0.jar").toString()), runtime.toString());

        // An artifact the lock repository lacks fails resolution with a pointer to the lock.
        Files.delete(lockRepository.resolve("com/example/dep/2.0/dep-2.0.jar"));
        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> {
            command.offline = true;
            command.noCache = true;
            command.localRepository = tempDir.resolve("offline-local-2");
            command.lockRepository = lockRepository;
        }));
        assertEquals(InstallExitCode.RESOLUTION_ERROR.code(), exitCode);
        String message = errors.toString(StandardCharsets.UTF_8);
        assertTrue(message.contains("com.example:dep:jar:2.0"), message);
        assertTrue(message.contains("only uses the lock repository"), message);
    }

    @Test
    void recordsSeededAndUntrackedArtifactsWithoutGuessingADownloadUrl() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository, "\"com.example:app:1.0\", \"io.micronaut.pyronaut:micronaut-pyronaut-logback:0.1.0\", \"com.other:copied:1.0\"");
        // Seeded from the SDK wheel or copied by hand: present in the local
        // repository without the _remote.repositories record of an origin.
        Path localRepository = tempDir.resolve("local");
        writeArtifact(localRepository, "io.micronaut.pyronaut", "micronaut-pyronaut-logback", "0.1.0", null, new byte[]{3});
        writeArtifact(localRepository, "com.other", "copied", "1.0", null, new byte[]{4});

        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        Map<String, DependencyLock.Entry> entries = new java.util.HashMap<>();
        DependencyLock.read(lockFile).forEach(entry -> entries.put(entry.path(), entry));
        DependencyLock.Entry bundled = entries.get("io/micronaut/pyronaut/micronaut-pyronaut-logback/0.1.0/micronaut-pyronaut-logback-0.1.0.jar");
        assertEquals(DependencyLock.BUNDLED_REPOSITORY, bundled.repository());
        assertEquals("", bundled.url());
        assertEquals(DependencyLock.sha256(localRepository.resolve(bundled.path())), bundled.sha256());
        DependencyLock.Entry copied = entries.get("com/other/copied/1.0/copied-1.0.pom");
        assertEquals(DependencyLock.LOCAL_REPOSITORY, copied.repository());
        assertEquals("", copied.url());
        assertFalse(Files.readString(lockFile).contains("url = \"\""));
        assertEquals(repository.toUri() + "com/example/app/1.0/app-1.0.jar",
            entries.get("com/example/app/1.0/app-1.0.jar").url());

        // A lock repository built only from the downloadable entries resolves
        // offline, taking the other entries from the local repository.
        Path lockRepository = tempDir.resolve("lock-repository");
        for (DependencyLock.Entry entry : entries.values()) {
            if (!entry.url().isEmpty()) {
                Path target = lockRepository.resolve(entry.path());
                Files.createDirectories(target.getParent());
                Files.copy(repository.resolve(entry.path()), target);
            }
        }
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> {
            command.offline = true;
            command.noCache = true;
            command.lockRepository = lockRepository;
        }));

        // Their checksums are still verified.
        Files.write(localRepository.resolve(bundled.path()), new byte[]{9});
        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> {
            command.offline = true;
            command.noCache = true;
            command.lockRepository = lockRepository;
        }));
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        assertTrue(errors.toString(StandardCharsets.UTF_8)
            .contains("io.micronaut.pyronaut:micronaut-pyronaut-logback:jar:0.1.0 does not match pyronaut.lock"));
    }

    @Test
    void rejectsConflictingOrInvalidLockOptions() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), captureErrors(errors, () -> install(project, command -> {
            command.writeLock = true;
            command.locked = true;
        })));
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("--write-lock cannot be combined"));

        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));
        errors.reset();
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), captureErrors(errors, () -> install(project, command ->
            command.lockRepository = Path.of("missing-directory"))));
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("is not a directory"));

        // A locked mode inherited from the environment does not apply while recording.
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> {
            command.writeLock = true;
            command.setEnvReader(Map.of(DependencyLock.LOCKED_ENV, "true", DependencyLock.LOCK_REPOSITORY_ENV, "missing")::get);
        }));
    }

    @Test
    void lockingIsRejectedForMavenAndGradleProjects() throws Exception {
        Path project = tempDir.resolve("maven-project");
        Files.createDirectories(project);
        Files.writeString(project.resolve("pom.xml"), "<project/>");

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), captureErrors(errors, () -> install(project, command -> command.writeLock = true)));
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("Dependency locking is not supported"), errors.toString(StandardCharsets.UTF_8));
    }

    @Test
    void verifyModeAcceptsAnUpToDateLockAndCachesTheResult() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> command.writeLock = true));

        Path lockFile = project.resolve(DependencyLock.FILE_NAME);
        DependencyLock lock = DependencyLock.open(lockFile, false, false, null);
        assertEquals(DependencyLock.Mode.VERIFY, lock.mode());
        assertFalse(lock.requiresResolution());
        assertTrue(lock.fingerprint().startsWith("VERIFY:"));
        assertEquals("off", DependencyLock.off().fingerprint());
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> { }));
        String hash = ResolutionCache.installHash(project.resolve("pyproject.toml"), tempDir.resolve("local"), lock.fingerprint());
        assertTrue(ResolutionCache.cacheHit(project.resolve("__pyronaut__"), hash, List.of(InstallScope.RUNTIME)));
        assertFalse(hash.equals(ResolutionCache.installHash(project.resolve("pyproject.toml"), tempDir.resolve("local"))));
    }

    @Test
    void quotesEveryStringItWrites() throws IOException {
        DependencyLock.Entry entry = new DependencyLock.Entry("odd\"\\\n\t\u0001name", "a/b/1/b-1.jar",
            "https://repo.example/", "", "a".repeat(64));
        Path file = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(file, DependencyLock.render(List.of(entry)));

        assertEquals(List.of(entry), DependencyLock.read(file));
    }

    @Test
    void readsEmptyLocksAndRejectsMalformedOnes() throws IOException {
        Path file = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(file, "version = 1\n");
        assertEquals(List.of(), DependencyLock.read(file));

        Files.writeString(file, "version = 1\nartifact = \"x\"\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("array of tables"));

        Files.writeString(file, "version = 1\n[[artifact]]\nsha256 = \"" + "a".repeat(64) + "\"\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().contains("every artifact requires path"));

        Files.writeString(file, "version = = 1\n");
        assertTrue(assertThrows(IllegalArgumentException.class, () -> DependencyLock.read(file))
            .getMessage().startsWith("Invalid "));
    }

    @Test
    void ignoresUnresolvedAndEditorOnlyArtifactsAndReportsUnreadableOnes() throws IOException {
        Path lockFile = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(lockFile, DependencyLock.render(List.of()));
        DependencyLock lock = DependencyLock.open(lockFile, false, true, null);
        org.eclipse.aether.artifact.Artifact unresolved = new org.eclipse.aether.artifact.DefaultArtifact("com.example:app:1.0");
        Path sourcesJar = Files.writeString(tempDir.resolve("app-1.0-sources.jar"), "sources");

        lock.artifactResolved(null, null);
        lock.artifactResolved(unresolved, null);
        lock.artifactResolved(new org.eclipse.aether.artifact.DefaultArtifact("com.example:app:jar:sources:1.0")
            .setPath(sourcesJar), null);
        lock.check();

        lock.artifactResolved(unresolved.setPath(tempDir.resolve("missing.jar")), null);
        PyprojectModelException failure = assertThrows(PyprojectModelException.class, lock::check);
        assertTrue(failure.getMessage().contains("Unable to compute the checksum of com.example:app:jar:1.0"), failure.getMessage());
    }

    @Test
    void summarizesManyViolations() throws IOException {
        Path lockFile = tempDir.resolve(DependencyLock.FILE_NAME);
        Files.writeString(lockFile, DependencyLock.render(List.of()));
        DependencyLock lock = DependencyLock.open(lockFile, false, true, null);
        Path jar = Files.writeString(tempDir.resolve("artifact.jar"), "jar");
        for (int i = 0; i < 25; i++) {
            lock.artifactResolved(new org.eclipse.aether.artifact.DefaultArtifact("com.example:lib" + i + ":1.0").setPath(jar), null);
        }

        PyprojectModelException failure = assertThrows(PyprojectModelException.class, lock::check);
        assertTrue(failure.getMessage().contains("(+5 more)"), failure.getMessage());
    }

    @Test
    void externalProjectsReuseTheirCachedLayoutWhenALockIsOnlyVerified() throws Exception {
        Path project = tempDir.resolve("gradle-project");
        Files.createDirectories(project);
        Files.writeString(project.resolve("build.gradle"), "plugins { id 'java' }\n");
        Files.writeString(project.resolve(DependencyLock.FILE_NAME), DependencyLock.render(List.of()));
        new io.micronaut.pyronaut.config.model.ExternalProjectLayout(
            io.micronaut.pyronaut.config.model.ExternalProjectLayout.ProjectKind.GRADLE,
            List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(), List.of(),
            false,
            List.of()
        ).write(project);
        Path cacheDir = io.micronaut.pyronaut.config.model.ExternalProjectLayout.outputDirectory(project);
        Files.writeString(cacheDir.resolve("external-build.sha256"),
            ResolutionCache.externalInstallHash(project, tempDir.resolve("local")));

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command -> command.progress = "auto"));

        assertEquals(InstallExitCode.SUCCESS.code(), exitCode, errors.toString(StandardCharsets.UTF_8));
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("dependencies already configured (cache hit)"));
    }

    @Test
    void lockModeIsReadFromTheEnvironment() throws Exception {
        Path repository = remoteRepository();
        Path project = project(repository);
        Path lockFile = tempDir.resolve("elsewhere/custom.lock");
        Map<String, String> env = Map.of(DependencyLock.LOCK_FILE_ENV, lockFile.toString());
        assertEquals(InstallExitCode.SUCCESS.code(), install(project, command -> {
            command.writeLock = true;
            command.setEnvReader(env::get);
        }));
        assertTrue(Files.isRegularFile(lockFile));
        assertFalse(Files.exists(project.resolve(DependencyLock.FILE_NAME)));

        ByteArrayOutputStream errors = new ByteArrayOutputStream();
        int exitCode = captureErrors(errors, () -> install(project, command ->
            command.setEnvReader(Map.of(DependencyLock.LOCKED_ENV, "true")::get)));
        assertEquals(InstallExitCode.CONFIG_ERROR.code(), exitCode);
        assertTrue(errors.toString(StandardCharsets.UTF_8).contains("does not exist"));
    }

    private int install(Path project, CommandCustomizer customizer) throws Exception {
        PyronautInstallMain command = new PyronautInstallMain(
            new PyprojectModelReader(),
            new MavenClasspathResolver(),
            new PyprojectEditorSupport(),
            new PythonEditorSupport(),
            new ExternalBuildResolver(),
            (model, localRepository, offline, refresh, listener) -> null
        );
        command.projectDir = project;
        command.scope = "runtime";
        command.progress = "off";
        command.localRepository = tempDir.resolve("local");
        command.setEnvReader(name -> null);
        customizer.customize(command);
        return command.call();
    }

    private Path remoteRepository() throws IOException {
        Path repository = tempDir.resolve("remote");
        writeArtifact(repository, "com.example", "app", "1.0", "com.example:dep:2.0", new byte[]{1});
        writeArtifact(repository, "com.example", "dep", "2.0", null, new byte[]{2});
        return repository;
    }

    private Path project(Path repository) throws IOException {
        return project(repository, "\"com.example:app:1.0\"");
    }

    private Path project(Path repository, String runtime) throws IOException {
        Path project = tempDir.resolve("project");
        Files.createDirectories(project);
        Files.writeString(project.resolve("pyproject.toml"), """
            [project]
            name = "lock-test"

            [tool.pyronaut]
            repositories = ["%s"]

            [tool.pyronaut.dependencies]
            runtime = [%s]
            build = []
            test = []

            [tool.pyronaut.test-resources]
            enabled = false
            """.formatted(repository.toUri(), runtime));
        return project;
    }

    private static void writeArtifact(Path repository,
                                      String groupId,
                                      String artifactId,
                                      String version,
                                      String dependency,
                                      byte[] jar) throws IOException {
        Path directory = repository.resolve(groupId.replace('.', '/')).resolve(artifactId).resolve(version);
        Files.createDirectories(directory);
        String dependencies = "";
        if (dependency != null) {
            String[] parts = dependency.split(":");
            dependencies = """
                  <dependencies>
                    <dependency>
                      <groupId>%s</groupId>
                      <artifactId>%s</artifactId>
                      <version>%s</version>
                    </dependency>
                  </dependencies>
                """.formatted(parts[0], parts[1], parts[2]);
        }
        Files.writeString(directory.resolve(artifactId + "-" + version + ".pom"), """
            <project xmlns="http://maven.apache.org/POM/4.0.0">
              <modelVersion>4.0.0</modelVersion>
              <groupId>%s</groupId>
              <artifactId>%s</artifactId>
              <version>%s</version>
            %s</project>
            """.formatted(groupId, artifactId, version, dependencies));
        Files.write(directory.resolve(artifactId + "-" + version + ".jar"), jar);
    }

    private static DependencyLock.Entry entry(String path, String name) {
        return new DependencyLock.Entry("org." + name + ":" + name + ":jar:1.0", path,
            "https://repo.example/", "https://repo.example/" + path, name.repeat(64).substring(0, 64).replaceAll("[^a-f]", "a"));
    }

    private static int captureErrors(ByteArrayOutputStream errors, ExitCodeAction action) throws Exception {
        PrintStream previous = System.err;
        System.setErr(new PrintStream(errors, true, StandardCharsets.UTF_8));
        try {
            return action.run();
        } finally {
            System.setErr(previous);
        }
    }

    private static void deleteRecursively(Path directory) throws IOException {
        try (var paths = Files.walk(directory)) {
            for (Path path : paths.sorted(java.util.Comparator.reverseOrder()).toList()) {
                Files.delete(path);
            }
        }
    }

    private static void restore(String property, String value) {
        if (value == null) {
            System.clearProperty(property);
        } else {
            System.setProperty(property, value);
        }
    }

    @FunctionalInterface
    private interface CommandCustomizer {
        void customize(PyronautInstallMain command);
    }

    @FunctionalInterface
    private interface ExitCodeAction {
        int run() throws Exception;
    }
}
