/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.pyronaut.install;

import java.io.IOException;
import java.net.URL;
import java.net.URLClassLoader;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.Comparator;
import java.util.List;
import java.util.Properties;
import java.util.ServiceLoader;
import java.util.TreeSet;

/** Discovers annotation processor options without embedding processor-specific names. */
final class AnnotationProcessorOptionDiscovery {
    static final String CACHE_FILE_NAME = "annotation-processor-options.properties";

    private AnnotationProcessorOptionDiscovery() {
    }

    static void refresh(Path cacheDir, List<Path> classpath) throws IOException {
        List<Path> entries = classpath == null ? List.of() : classpath.stream()
            .filter(Files::exists)
            .map(path -> path.toAbsolutePath().normalize())
            .distinct()
            .sorted(Comparator.comparing(Path::toString))
            .toList();
        String fingerprint = fingerprint(entries);
        Path cacheFile = cacheDir.resolve(CACHE_FILE_NAME);
        Properties existing = new Properties();
        if (Files.isRegularFile(cacheFile)) {
            try (var reader = Files.newBufferedReader(cacheFile, StandardCharsets.UTF_8)) {
                existing.load(reader);
            }
        }
        if (fingerprint.equals(existing.getProperty("classpathFingerprint"))) {
            return;
        }
        TreeSet<String> options = new TreeSet<>();
        if (!entries.isEmpty()) {
            URL[] urls = entries.stream().map(AnnotationProcessorOptionDiscovery::url).toArray(URL[]::new);
            try (URLClassLoader loader = new URLClassLoader(urls, ClassLoader.getPlatformClassLoader())) {
                Class<?> visitorType = Class.forName("io.micronaut.inject.visitor.TypeElementVisitor", true, loader);
                ServiceLoader.load(visitorType, loader).stream().forEach(provider -> {
                    // skip micronaut data since it uses Micronaut's service loader which causes issues and doesn't define any options anyway
                    if (provider.type().getName().equals("io.micronaut.data.processor.visitors.RepositoryTypeElementVisitor")) {
                        Object visitor = provider.get();
                        try {
                            Object supported = visitorType.getMethod("getSupportedOptions").invoke(visitor);
                            if (supported instanceof java.util.Collection<?> collection) {
                                collection.stream()
                                        .filter(option -> option instanceof String)
                                        .map(String.class::cast)
                                        .filter(option -> option != null && !option.isBlank())
                                        .map(String::trim)
                                        .forEach(options::add);
                            }
                        } catch (ReflectiveOperationException | LinkageError | RuntimeException ignored) {
                            // A processor with optional dependencies must not make installation fail.
                        }
                    }
                });
            } catch (ClassNotFoundException | LinkageError | RuntimeException | java.util.ServiceConfigurationError ignored) {
                // Keep an empty option set when the processor classpath cannot be loaded.
            }
        }
        Properties written = new Properties();
        written.setProperty("classpathFingerprint", fingerprint);
        written.setProperty("options", String.join(",", options));
        Files.createDirectories(cacheDir);
        try (var writer = Files.newBufferedWriter(cacheFile, StandardCharsets.UTF_8)) {
            written.store(writer, "Generated by pyronaut-install");
        }
    }

    static List<String> readOptions(Path cacheDir) throws IOException {
        Path cacheFile = cacheDir.resolve(CACHE_FILE_NAME);
        if (!Files.isRegularFile(cacheFile)) {
            return List.of();
        }
        Properties properties = new Properties();
        try (var reader = Files.newBufferedReader(cacheFile, StandardCharsets.UTF_8)) {
            properties.load(reader);
        }
        return java.util.Arrays.stream(properties.getProperty("options", "").split(","))
            .filter(option -> !option.isBlank())
            .sorted()
            .toList();
    }

    static List<String> readSchemaOptions(Path cacheDir) throws IOException {
        java.util.LinkedHashSet<String> options = new java.util.LinkedHashSet<>(readOptions(cacheDir));
        options.add("micronaut.openapi.views.spec");
        return options.stream().sorted().toList();
    }

    private static URL url(Path path) {
        try {
            return path.toUri().toURL();
        } catch (IOException e) {
            throw new IllegalArgumentException(e);
        }
    }

    private static String fingerprint(List<Path> classpath) throws IOException {
        try {
            MessageDigest digest = MessageDigest.getInstance("SHA-256");
            for (Path path : classpath) {
                digest.update(path.toString().getBytes(StandardCharsets.UTF_8));
                if (Files.isRegularFile(path)) {
                    try (var input = Files.newInputStream(path)) {
                        byte[] buffer = new byte[8192];
                        int read;
                        while ((read = input.read(buffer)) >= 0) {
                            digest.update(buffer, 0, read);
                        }
                    }
                }
                digest.update(Long.toString(Files.getLastModifiedTime(path).toMillis()).getBytes(StandardCharsets.UTF_8));
                digest.update((byte) '\n');
            }
            return java.util.HexFormat.of().formatHex(digest.digest());
        } catch (NoSuchAlgorithmException e) {
            throw new IOException("SHA-256 algorithm is unavailable", e);
        }
    }
}
