/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.pyronaut.install;

import io.micronaut.pyronaut.config.model.PyprojectJsonSchemaGenerator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;

/**
 * Writes editor support files for TOML configuration.
 */
final class PyprojectEditorSupport {
    static final String TAPLO_FILE_NAME = ".taplo.toml";
    private static final String GENERATED_MARKER = "# Generated by pyronaut-install for Pyronaut TOML schema support.";
    private static final String PYPROJECT_SCHEMA_RELATIVE_PATH = "__pyronaut__/schemas/" + PyprojectJsonSchemaGenerator.SCHEMA_FILE_NAME;
    private static final String PYPROJECT_SCHEMA_DIRECTIVE = "#:schema ./" + PYPROJECT_SCHEMA_RELATIVE_PATH;
    private static final String APPLICATION_SCHEMA_RELATIVE_PATH = "../__pyronaut__/schemas/" + MicronautApplicationJsonSchemaBundler.SCHEMA_FILE_NAME;
    private static final String APPLICATION_SCHEMA_DIRECTIVE = "#:schema " + APPLICATION_SCHEMA_RELATIVE_PATH;

    private final PyprojectJsonSchemaGenerator schemaGenerator;
    private final MicronautApplicationJsonSchemaBundler applicationSchemaBundler;

    PyprojectEditorSupport() {
        this(new PyprojectJsonSchemaGenerator(), new MicronautApplicationJsonSchemaBundler());
    }

    PyprojectEditorSupport(PyprojectJsonSchemaGenerator schemaGenerator) {
        this(schemaGenerator, new MicronautApplicationJsonSchemaBundler());
    }

    PyprojectEditorSupport(PyprojectJsonSchemaGenerator schemaGenerator,
                           MicronautApplicationJsonSchemaBundler applicationSchemaBundler) {
        this.schemaGenerator = schemaGenerator;
        this.applicationSchemaBundler = applicationSchemaBundler;
    }

    void ensureWritten(Path projectDir, Path cacheDir) throws IOException {
        schemaGenerator.write(cacheDir.resolve("schemas").resolve(PyprojectJsonSchemaGenerator.SCHEMA_FILE_NAME));
        ensureManagedDirective(
            projectDir.resolve("pyproject.toml"),
            pyprojectManagedDirectiveBlock(),
            PYPROJECT_SCHEMA_DIRECTIVE
        );
        ensureApplicationSchemaFromManifest(projectDir, cacheDir);
        deleteGeneratedTaploFileIfPresent(projectDir.resolve(TAPLO_FILE_NAME));
    }

    MicronautApplicationJsonSchemaBundler.SchemaWriteResult ensureApplicationSchema(Path projectDir,
                                                                                    Path cacheDir,
                                                                                    List<String> runtimeClasspath) throws IOException {
        Path schemaFile = cacheDir.resolve("schemas").resolve(MicronautApplicationJsonSchemaBundler.SCHEMA_FILE_NAME);
        MicronautApplicationJsonSchemaBundler.SchemaWriteResult result = applicationSchemaBundler.write(runtimeClasspath, schemaFile);
        if (result.available()) {
            ensureApplicationDirective(projectDir.resolve("config").resolve("application.toml"));
        }
        return result;
    }

    MicronautApplicationJsonSchemaBundler.SchemaWriteResult ensureApplicationSchemaFromManifest(Path projectDir,
                                                                                                Path cacheDir) throws IOException {
        Path schemaFile = cacheDir.resolve("schemas").resolve(MicronautApplicationJsonSchemaBundler.SCHEMA_FILE_NAME);
        Path manifestFile = cacheDir.resolve(InstallScope.RUNTIME.manifestFile());
        MicronautApplicationJsonSchemaBundler.SchemaWriteResult result = applicationSchemaBundler.writeFromManifest(manifestFile, schemaFile);
        if (result.available()) {
            ensureApplicationDirective(projectDir.resolve("config").resolve("application.toml"));
        }
        return result;
    }

    private static void ensureApplicationDirective(Path applicationToml) throws IOException {
        if (!Files.exists(applicationToml)) {
            return;
        }
        ensureManagedDirective(applicationToml, applicationManagedDirectiveBlock(), APPLICATION_SCHEMA_DIRECTIVE);
    }

    private static void ensureManagedDirective(Path file,
                                               String content,
                                               String schemaDirective) throws IOException {
        String existing = Files.readString(file, StandardCharsets.UTF_8);
        if (existing.startsWith(content)) {
            return;
        }
        if (isManagedDirective(existing, schemaDirective)) {
            int bodyStart = existing.indexOf("\n\n");
            String remainder = bodyStart >= 0 ? existing.substring(bodyStart + 2) : "";
            Files.writeString(file, content + remainder, StandardCharsets.UTF_8);
            return;
        }
        if (existing.startsWith("#:schema ")) {
            return;
        }
        Files.writeString(file, content + existing, StandardCharsets.UTF_8);
    }

    private static void deleteGeneratedTaploFileIfPresent(Path taploFile) throws IOException {
        if (!Files.exists(taploFile)) {
            return;
        }
        String existing = Files.readString(taploFile, StandardCharsets.UTF_8);
        if (existing.startsWith(GENERATED_MARKER)) {
            Files.deleteIfExists(taploFile);
        }
    }

    static String managedDirectiveBlock() {
        return pyprojectManagedDirectiveBlock();
    }

    static String pyprojectManagedDirectiveBlock() {
        return PYPROJECT_SCHEMA_DIRECTIVE + "\n"
            + GENERATED_MARKER + "\n\n";
    }

    static String applicationManagedDirectiveBlock() {
        return APPLICATION_SCHEMA_DIRECTIVE + "\n"
            + GENERATED_MARKER + "\n\n";
    }

    private static boolean isManagedDirective(String content, String schemaDirective) {
        return content.startsWith(schemaDirective + "\n" + GENERATED_MARKER + "\n");
    }
}
