/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.pyronaut.install;

import io.micronaut.pyronaut.config.model.PyprojectJsonSchemaGenerator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;

/**
 * Writes editor support files for {@code pyproject.toml}.
 */
final class PyprojectEditorSupport {
    static final String TAPLO_FILE_NAME = ".taplo.toml";
    private static final String GENERATED_MARKER = "# Generated by pyronaut-install for Pyronaut TOML schema support.";
    private static final String SCHEMA_RELATIVE_PATH = "__pyronaut__/schemas/" + PyprojectJsonSchemaGenerator.SCHEMA_FILE_NAME;
    private static final String SCHEMA_DIRECTIVE = "#:schema ./" + SCHEMA_RELATIVE_PATH;

    private final PyprojectJsonSchemaGenerator schemaGenerator;

    PyprojectEditorSupport() {
        this(new PyprojectJsonSchemaGenerator());
    }

    PyprojectEditorSupport(PyprojectJsonSchemaGenerator schemaGenerator) {
        this.schemaGenerator = schemaGenerator;
    }

    void ensureWritten(Path projectDir, Path cacheDir) throws IOException {
        schemaGenerator.write(cacheDir.resolve("schemas").resolve(PyprojectJsonSchemaGenerator.SCHEMA_FILE_NAME));
        ensurePyprojectDirective(projectDir.resolve("pyproject.toml"));
        deleteGeneratedTaploFileIfPresent(projectDir.resolve(TAPLO_FILE_NAME));
    }

    private static void ensurePyprojectDirective(Path pyprojectFile) throws IOException {
        String existing = Files.readString(pyprojectFile, StandardCharsets.UTF_8);
        String content = managedDirectiveBlock();
        if (existing.startsWith(content)) {
            return;
        }
        if (isManagedDirective(existing)) {
            int bodyStart = existing.indexOf("\n\n");
            String remainder = bodyStart >= 0 ? existing.substring(bodyStart + 2) : "";
            Files.writeString(pyprojectFile, content + remainder, StandardCharsets.UTF_8);
            return;
        }
        if (existing.startsWith("#:schema ")) {
            return;
        }
        Files.writeString(pyprojectFile, content + existing, StandardCharsets.UTF_8);
    }

    private static void deleteGeneratedTaploFileIfPresent(Path taploFile) throws IOException {
        if (!Files.exists(taploFile)) {
            return;
        }
        String existing = Files.readString(taploFile, StandardCharsets.UTF_8);
        if (existing.startsWith(GENERATED_MARKER)) {
            Files.deleteIfExists(taploFile);
        }
    }

    static String managedDirectiveBlock() {
        return SCHEMA_DIRECTIVE + "\n"
            + GENERATED_MARKER + "\n\n";
    }

    private static boolean isManagedDirective(String content) {
        return content.startsWith(SCHEMA_DIRECTIVE + "\n" + GENERATED_MARKER + "\n");
    }
}
