/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.pyronaut.install;

import io.micronaut.pyronaut.config.model.PyprojectModel;
import io.micronaut.pyronaut.config.model.PyprojectJsonSchemaGenerator;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;

/**
 * Writes editor support files for TOML configuration.
 */
final class PyprojectEditorSupport {
    static final String TAPLO_FILE_NAME = ".taplo.toml";
    private static final String GENERATED_MARKER = "# Generated by pyronaut-install for Pyronaut TOML schema support.";
    private static final String PYPROJECT_SCHEMA_RELATIVE_PATH = "__pyronaut__/schemas/" + PyprojectJsonSchemaGenerator.SCHEMA_FILE_NAME;
    private static final String PYPROJECT_SCHEMA_DIRECTIVE = "#:schema ./" + PYPROJECT_SCHEMA_RELATIVE_PATH;

    private final PyprojectJsonSchemaGenerator schemaGenerator;
    private final MicronautApplicationJsonSchemaBundler applicationSchemaBundler;

    PyprojectEditorSupport() {
        this(new PyprojectJsonSchemaGenerator(), new MicronautApplicationJsonSchemaBundler());
    }

    PyprojectEditorSupport(PyprojectJsonSchemaGenerator schemaGenerator) {
        this(schemaGenerator, new MicronautApplicationJsonSchemaBundler());
    }

    PyprojectEditorSupport(PyprojectJsonSchemaGenerator schemaGenerator,
                           MicronautApplicationJsonSchemaBundler applicationSchemaBundler) {
        this.schemaGenerator = schemaGenerator;
        this.applicationSchemaBundler = applicationSchemaBundler;
    }

    void ensureWritten(Path projectDir, Path cacheDir, PyprojectModel.Sources sources) throws IOException {
        Path pyprojectSchema = cacheDir.resolve("schemas").resolve(PyprojectJsonSchemaGenerator.SCHEMA_FILE_NAME);
        schemaGenerator.write(pyprojectSchema);
        ensureManagedDirective(
            projectDir.resolve("pyproject.toml"),
            pyprojectManagedDirectiveBlock(),
            PYPROJECT_SCHEMA_DIRECTIVE
        );
        ensureApplicationSchemaFromManifest(projectDir, cacheDir, sources);
        deleteGeneratedTaploFileIfPresent(projectDir.resolve(TAPLO_FILE_NAME));
    }

    MicronautApplicationJsonSchemaBundler.SchemaWriteResult ensureApplicationSchema(Path projectDir,
                                                                                    Path cacheDir,
                                                                                    PyprojectModel.Sources sources,
                                                                                    List<String> runtimeClasspath) throws IOException {
        return ensureApplicationSchema(projectDir, cacheDir, sources, runtimeClasspath, List.of());
    }

    MicronautApplicationJsonSchemaBundler.SchemaWriteResult ensureApplicationSchema(Path projectDir,
                                                                                    Path cacheDir,
                                                                                    PyprojectModel.Sources sources,
                                                                                    List<String> runtimeClasspath,
                                                                                    List<String> processorOptions) throws IOException {
        Path schemaFile = cacheDir.resolve("schemas").resolve(MicronautApplicationJsonSchemaBundler.SCHEMA_FILE_NAME);
        MicronautApplicationJsonSchemaBundler.SchemaWriteResult result = applicationSchemaBundler.write(runtimeClasspath, schemaFile, processorOptions);
        if (result.available()) {
            ensureApplicationDirective(projectDir, schemaFile, sources);
        }
        return result;
    }

    MicronautApplicationJsonSchemaBundler.SchemaWriteResult ensureApplicationSchemaFromManifest(Path projectDir,
                                                                                                Path cacheDir,
                                                                                                PyprojectModel.Sources sources) throws IOException {
        Path schemaFile = cacheDir.resolve("schemas").resolve(MicronautApplicationJsonSchemaBundler.SCHEMA_FILE_NAME);
        Path manifestFile = cacheDir.resolve(InstallScope.RUNTIME.manifestFile());
        MicronautApplicationJsonSchemaBundler.SchemaWriteResult result = applicationSchemaBundler.write(
            Files.exists(manifestFile) ? Files.readAllLines(manifestFile, StandardCharsets.UTF_8) : List.of(),
            schemaFile,
            AnnotationProcessorOptionDiscovery.readSchemaOptions(cacheDir)
        );
        if (result.available()) {
            ensureApplicationDirective(projectDir, schemaFile, sources);
        }
        return result;
    }

    private static void ensureApplicationDirective(Path projectDir,
                                                   Path schemaFile,
                                                   PyprojectModel.Sources sources) throws IOException {
        Path applicationToml = resolveApplicationToml(projectDir, sources);
        if (!Files.exists(applicationToml)) {
            return;
        }
        ensureManagedDirective(applicationToml, applicationManagedDirectiveBlock(schemaFile, applicationToml), applicationSchemaDirective(schemaFile, applicationToml));
    }

    private static void ensureManagedDirective(Path file,
                                               String content,
                                               String schemaDirective) throws IOException {
        String existing = Files.readString(file, StandardCharsets.UTF_8);
        if (existing.startsWith(content)) {
            return;
        }
        if (isManagedDirective(existing, schemaDirective)) {
            int bodyStart = existing.indexOf("\n\n");
            String remainder = bodyStart >= 0 ? existing.substring(bodyStart + 2) : "";
            Files.writeString(file, content + remainder, StandardCharsets.UTF_8);
            return;
        }
        if (existing.startsWith("#:schema ")) {
            return;
        }
        Files.writeString(file, content + existing, StandardCharsets.UTF_8);
    }

    private static void deleteGeneratedTaploFileIfPresent(Path taploFile) throws IOException {
        if (!Files.exists(taploFile)) {
            return;
        }
        String existing = Files.readString(taploFile, StandardCharsets.UTF_8);
        if (existing.startsWith(GENERATED_MARKER)) {
            Files.deleteIfExists(taploFile);
        }
    }

    static String managedDirectiveBlock() {
        return pyprojectManagedDirectiveBlock();
    }

    static String pyprojectManagedDirectiveBlock() {
        return PYPROJECT_SCHEMA_DIRECTIVE + "\n"
            + GENERATED_MARKER + "\n\n";
    }

    static String applicationManagedDirectiveBlock() {
        return "#:schema ../__pyronaut__/schemas/" + MicronautApplicationJsonSchemaBundler.SCHEMA_FILE_NAME + "\n"
            + GENERATED_MARKER + "\n\n";
    }

    static String applicationManagedDirectiveBlock(Path schemaFile, Path applicationToml) {
        return applicationSchemaDirective(schemaFile, applicationToml) + "\n"
            + GENERATED_MARKER + "\n\n";
    }

    private static String applicationSchemaDirective(Path schemaFile, Path applicationToml) {
        Path relative = applicationToml.getParent().relativize(schemaFile);
        return "#:schema " + toForwardSlash(relative);
    }

    private static Path resolveApplicationToml(Path projectDir, PyprojectModel.Sources sources) {
        Path resourcesDir = Paths.get(sources.resources());
        Path resolvedResources = resourcesDir.isAbsolute() ? resourcesDir.normalize() : projectDir.resolve(resourcesDir).normalize();
        return resolvedResources.resolve("application.toml");
    }

    private static String toForwardSlash(Path path) {
        return path.toString().replace('\\', '/');
    }

    private static boolean isManagedDirective(String content, String schemaDirective) {
        return content.startsWith(schemaDirective + "\n" + GENERATED_MARKER + "\n");
    }
}
