import importlib.util
import io
import sys
import tempfile
import types
import unittest
from contextlib import redirect_stderr, redirect_stdout
from pathlib import Path
from unittest.mock import patch

_CLI_MODULE_PATH = Path(__file__).resolve().parents[2] / "main" / "python" / "pyronaut_cli_v2" / "cli.py"
_CLI_SPEC = importlib.util.spec_from_file_location("pyronaut_cli_v2.cli", _CLI_MODULE_PATH)
if _CLI_SPEC is None or _CLI_SPEC.loader is None:
    raise RuntimeError("Failed loading pyronaut_cli_v2.cli for tests")
if str(_CLI_MODULE_PATH.parent.parent) not in sys.path:
    sys.path.insert(0, str(_CLI_MODULE_PATH.parent.parent))

sys.modules.pop("pyronaut_cli_v2", None)
pkg = types.ModuleType("pyronaut_cli_v2")
pkg.__path__ = [str(_CLI_MODULE_PATH.parent)]
sys.modules["pyronaut_cli_v2"] = pkg

cli = importlib.util.module_from_spec(_CLI_SPEC)
_CLI_SPEC.loader.exec_module(cli)

_LOCK = """# This file is generated by `pyronaut lock`. Do not edit it by hand.
version = 1

[[artifact]]
coordinates = "com.example:app:jar:1.0"
path = "com/example/app/1.0/app-1.0.jar"
repository = "https://repo1.maven.org/maven2/"
url = "https://repo1.maven.org/maven2/com/example/app/1.0/app-1.0.jar"
sha256 = "%s"
""" % ("a" * 64)


def _option(command_line, name):
    return command_line[command_line.index(name) + 1]


class LockCommandTest(unittest.TestCase):
    def setUp(self):
        temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(temp_dir.cleanup)
        self.project = Path(temp_dir.name).resolve() / "app"
        self.project.mkdir()
        (self.project / "pyproject.toml").write_text('[project]\nname = "app"\n', encoding="utf-8")
        self.executed = []
        for name, value in (("_setup_is_required", lambda: False),
                            ("_seed_bundled_pyronaut_maven_repository", lambda *args, **kwargs: None)):
            patcher = patch.object(cli, name, side_effect=value)
            patcher.start()
            self.addCleanup(patcher.stop)

    def _runner(self, lock_contents=_LOCK, exit_code=0):
        def runner(command_line, env=None):
            self.executed.append(list(command_line))
            if "--write-lock" in command_line and lock_contents is not None:
                Path(_option(command_line, "--lock-file")).write_text(lock_contents, encoding="utf-8")
            return exit_code

        return runner

    def _run(self, args, runner):
        stdout, stderr = io.StringIO(), io.StringIO()
        with redirect_stdout(stdout), redirect_stderr(stderr):
            code = cli.run(
                ["lock", "--project-dir", str(self.project), *args],
                runner_with_env=runner,
                resolver=lambda name: f"/tmp/{name}",
                platform_name="linux",
                java_home_provider=lambda *args, **kwargs: "/opt/graalvm",
            )
        return code, stdout.getvalue(), stderr.getvalue()

    def test_writes_lock_recorded_by_the_installer(self):
        code, stdout, stderr = self._run(["--offline"], self._runner())

        self.assertEqual(cli.SUCCESS, code, stderr)
        self.assertEqual(_LOCK, (self.project / "pyronaut.lock").read_text(encoding="utf-8"))
        self.assertIn("(1 artifacts)", stdout)
        install = self.executed[-1]
        self.assertEqual("/tmp/pyronaut-install", install[0])
        self.assertEqual(str(self.project), _option(install, "--project-dir"))
        self.assertIn("--write-lock", install)
        self.assertIn("--offline", install)
        # The installer records into a temporary file that only replaces
        # pyronaut.lock once resolution succeeded.
        self.assertNotEqual(str(self.project / "pyronaut.lock"), _option(install, "--lock-file"))
        self.assertEqual([], [path.name for path in self.project.iterdir() if path.name.startswith(".pyronaut-lock-")])

    def test_keeps_existing_lock_when_resolution_fails(self):
        (self.project / "pyronaut.lock").write_text("previous", encoding="utf-8")

        code, _, _ = self._run([], self._runner(exit_code=3))

        self.assertEqual(3, code)
        self.assertEqual("previous", (self.project / "pyronaut.lock").read_text(encoding="utf-8"))

    def test_check_reports_missing_or_stale_lock_without_writing(self):
        code, _, stderr = self._run(["--check"], self._runner())
        self.assertEqual(cli.PRECONDITION_FAILED, code)
        self.assertIn("is missing", stderr)
        self.assertFalse((self.project / "pyronaut.lock").exists())

        (self.project / "pyronaut.lock").write_text(_LOCK.replace("1.0", "0.9"), encoding="utf-8")
        code, _, stderr = self._run(["--check"], self._runner())
        self.assertEqual(cli.PRECONDITION_FAILED, code)
        self.assertIn("is out of date", stderr)

        (self.project / "pyronaut.lock").write_text(_LOCK, encoding="utf-8")
        code, stdout, _ = self._run(["--check"], self._runner())
        self.assertEqual(cli.SUCCESS, code)
        self.assertIn("is up to date", stdout)

    def test_requires_a_pyproject_project(self):
        (self.project / "pyproject.toml").unlink()
        (self.project / "pom.xml").write_text("<project/>", encoding="utf-8")

        code, _, stderr = self._run([], self._runner())

        self.assertEqual(cli.PRECONDITION_FAILED, code)
        self.assertIn("does not support Maven or Gradle projects", stderr)
        self.assertEqual([], self.executed)

    def test_rejects_unknown_options(self):
        code, _, stderr = self._run(["--locked"], self._runner())
        self.assertEqual(cli.USAGE_ERROR, code)
        self.assertIn("Unknown pyronaut lock option: --locked", stderr)

    def test_records_sdk_launcher_classpaths_before_the_project(self):
        manifest = {
            "javaHome": "/opt/graalvm",
            "repositories": ["mavenCentral"],
            "images": {name: {"executable": f"/opt/{name}"} for name in cli._SETUP_IMAGE_COMMANDS},
        }
        descriptor = "maven\tcom.example\ttool\t1.0\tjar\t\ttool-1.0.jar"
        with patch.object(cli, "_setup_is_required", return_value=True), \
                patch.object(cli, "_read_valid_setup_manifest", return_value=manifest), \
                patch.object(cli, "_bundled_executable", return_value="/opt/pyronaut-install"), \
                patch.object(cli, "_is_executable_file", return_value=True), \
                patch.object(cli, "_require_setup", return_value=True), \
                patch.object(cli, "_native_compile_descriptor_entries", return_value=[descriptor]):
            code, _, stderr = self._run([], self._runner())

        self.assertEqual(cli.SUCCESS, code, stderr)
        self.assertEqual(2, len(self.executed))
        sdk, project = self.executed
        self.assertEqual("/opt/pyronaut-install", sdk[0])
        self.assertIn("--resolve-tools-only", sdk)
        self.assertEqual("mavenCentral", _option(sdk, "--repository"))
        self.assertIn("--write-lock", sdk)
        # Both invocations record into the same lock.
        self.assertEqual(_option(sdk, "--lock-file"), _option(project, "--lock-file"))

    def test_setup_accepts_locked(self):
        cli._validate_setup_arguments(["--locked", "--offline"])
        _, env = cli._sdk_tool_resolution_invocation(
            "/opt/pyronaut-install", Path("/tmp/request"), "/tmp/m2", ["mavenCentral"], "/opt/graalvm",
            offline=False, refresh=False, progress_mode="off", locked=True,
        )
        command_line, _ = cli._sdk_tool_resolution_invocation(
            "/opt/pyronaut-install", Path("/tmp/request"), "/tmp/m2", ["mavenCentral"], "/opt/graalvm",
            offline=False, refresh=False, progress_mode="off", locked=True,
        )
        self.assertIn("--locked", command_line)
        self.assertEqual("/opt/graalvm", env["JAVA_HOME"])

    def test_lock_options_are_not_direct_sources(self):
        self.assertFalse(cli._has_direct_install_sources(
            ["--project-dir", "app", "--locked", "--lock-file", "app.lock", "--lock-repository", "vendor/m2"]
        ))

    def test_lock_help(self):
        stdout = io.StringIO()
        with redirect_stdout(stdout):
            code = cli.run(["lock", "--help"], resolver=lambda name: None, platform_name="linux")
        self.assertEqual(cli.SUCCESS, code)
        self.assertIn("Usage: pyronaut lock", stdout.getvalue())


if __name__ == "__main__":
    unittest.main()
