[project]
name = "pyronaut-e2e"
version = "1.0.0"
dynamic = ["scripts"]

[build-system]
requires = ["setuptools", "wheel", "tomli"]
build-backend = "setuptools.build_meta"

[tool.pyronaut]
version = "5.0.0-SNAPSHOT"
repositories = [
  "mavenCentral",
  "https://repo.gradle.org/gradle/libs-releases"
]

[tool.pyronaut.testResources]
enabled = true
version = "2.9.0"

[tool.pyronaut.dependencies]
runtime = [
  "io.micronaut:micronaut-http-server-netty",
  "io.micronaut:micronaut-json-core",
  "io.micronaut:micronaut-jackson-databind",
  "org.bouncycastle:bcprov-jdk18on:1.82",
  "org.apache.commons:commons-lang3:3.20.0",
  "ch.qos.logback:logback-classic"
]
build = [
]
test = [
  "io.micronaut:micronaut-pytest-engine:5.0.0-SNAPSHOT",
  "io.micronaut.test:micronaut-test-junit5"
]
